backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "Fruit"
    label: "Fruit"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Fruit Name", name: "Fruit Name", widget: "string" }
      - {
          label: "Brief Description",
          name: "Brief Description",
          widget: "string",
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "In Stock", name: "In Stock", widget: "boolean" }
      - { label: "Fruit Image", name: "Fruit Image", widget: image }

      - { label: "Price", name: "Price", widget: "Number" }
